[package]
name = "hydra-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
reflink-copy.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
