[package]
name = "hydra-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "hydra"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
hydra-core = { path = "../hydra-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true

[lints]
workspace = true
